In [11]:
import sys

import torch
import numpy as np

from attacks import AttackContainer
from basemodels import TorchModelContainer, BCNN, MnistCnnCW
from datasets import (DATASET_LIST, DataContainer, get_image_list,
                      get_quantitative_list, scale_unnormalize)
from defences import DefenceContainer

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
print(sys.version)
print(*sys.path, sep='\n')

3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload

/home/lukec/venv/lib/python3.6/site-packages
/home/lukec/Downloads/jax/build
/home/lukec/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/lukec/venv/lib/python3.6/site-packages/IPython/extensions
/home/lukec/.ipython


In [4]:
print('Avaliable image datasets:')
print(get_image_list())
print()
print('Avaliable quantitative datasets:')
print(get_quantitative_list())
print()

Avaliable image datasets:
['MNIST', 'CIFAR10', 'SVHN']

Avaliable quantitative datasets:
['BankNote', 'BreastCancerWisconsin', 'HTRU2', 'Iris', 'WheatSeed']



In [5]:
DATA_ROOT = 'data'
BATCH_SIZE = 128
# TYPE in {'image', 'quantitative'}
TYPE = 'quantitative' 

# image in {'MNIST', 'CIFAR10', 'SVHN'}
# quantitative in {'BankNote', 'BreastCancerWisconsin', 'HTRU2', 'Iris', 'WheatSeed'}
NAME = 'BankNote'
print(f'Starting {NAME} data container...')
IMAGE_DATASET = DATASET_LIST[TYPE][NAME]
print(IMAGE_DATASET)

Starting BankNote data container...
{'name': 'BankNote', 'type': 'quantitative', 'size': 1372, 'num_classes': 2, 'dim_data': (4,)}


In [8]:
dc = DataContainer(IMAGE_DATASET, DATA_ROOT)
dc(BATCH_SIZE, normalize=True)

Loading data...
Preparing DataFrame...
Reading from data/data_banknote_authentication.txt
Spliting train/test sets into numpy arrays...
Preparing DataLoaders...
Successfully load data! Time taken:  0m 0.0s


In [9]:
num_features = dc.dim_data[0]
num_classes = dc.num_classes

print('Features:', num_features)
print('Classes:', num_classes)

Features: 4
Classes: 2


In [12]:
# model in {BCNN, MnistCnnCW}
model = BCNN(num_features, num_classes)
model_name = model.__class__.__name__
print('Using model:', model_name)

Using model: BCNN


In [13]:
dc.data_range

(array([ -7.04209995, -13.7730999 ,  -5.28609991,  -8.54819965]),
 array([ 6.82480001, 12.95160007, 17.92740059,  2.44950008]))

In [22]:
dc.data_test_np[:3]

array([[0.33887172, 1.        , 0.37110302, 0.23692226],
       [0.69301   , 0.64684355, 0.25416934, 0.74027205],
       [0.22761397, 0.03468701, 0.77893466, 0.49218473]], dtype=float32)

In [23]:
scale_unnormalize(dc.data_test_np[:3], dc.data_range[0], dc.data_range[1])

array([[ -2.34299975,  12.95160007,   3.3285002 ,  -5.94259973],
       [  2.56780001,   3.51359997,   0.6140603 ,  -0.40690998],
       [ -3.88579979, -12.8460999 ,  12.79570015,  -3.1352998 ]])